[package]
name = "bspwm-grid"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[dependencies]
argh = "0.1"
thiserror = "1.0"
itertools = "0.10.5"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
